import {
  WHITE,
  BLUEBERRY_SODA,
  LYNX_WHITE,
  DOWNLOAD_PROGRESS,
  PROTOSS_PYLON,
} from '../theme/colors';

export const RIGHT_PANE_BACKGROUND = WHITE;
export const ICON_COLOR = BLUEBERRY_SODA;
export const MAIN_CONTAINER_BACKGROUND = LYNX_WHITE;
export const ERROR_SCREEN_BACKGROUND = LYNX_WHITE;
export const ERROR_SCREEN_ICON_COLOR = BLUEBERRY_SODA;
export const Error_SCREEN_TEXT_COLOR = BLUEBERRY_SODA;
export const TOP_BAR_COLOR = WHITE;
export const STRUCTURE_COLOR = BLUEBERRY_SODA;
export const HIGHLIGHTED_STRUCTURE_COLOR = PROTOSS_PYLON;
export const SELECTED_STRUCTURE_COLOR = DOWNLOAD_PROGRESS;
