export const UPDATE_STATE = new Event('UPDATE_STATE');

export const UPDATE_NAME = new Event('UPDATE_NAME');

export const UPDATE_DESCRIPTION = new Event('UPDATE_DESCRIPTION');

export const UPDATE_COORDINATES = new Event('UPDATE_COORDINATES');

export const UPDATE_NODES = new Event('UPDATE_NODES');

export const UPDATE_STRUCTURES = new Event('UPDATE_STRUCTURES');
export const UPDATE_SELECTED_STRUCTURE_ID = new Event(
  'UPDATE_SELECTED_STRUCTURE_ID'
);

export const UPDATE_EXPERIMENTS = new Event('UPDATE_EXPERIMENTS');
export const UPDATE_SELECTED_EXPERIMENT_ID = new Event(
  'UPDATE_SELECTED_EXPERIMENT_ID'
);

export const UPDATE_MONITORS = new Event('UPDATE_MONITORS');
export const UPDATE_SELECTED_MONITOR_ID = new Event(
  'UPDATE_SELECTED_MONITOR_ID'
);

export const UPDATE_STRUCTURE_EDITOR_CONTEXT = new Event(
  'UPDATE_SELECTED_STRUCTURE_EDITOR_CONTEXT'
);
export const UPDATE_EXPERIMENT_EDITOR_CONTEXT = new Event(
  'UPDATE_EXPERIMENT_EDITOR_CONTEXT'
);
