export const UPDATE_STATE = new Event('SET_STATE');
export const UPDATE_STRUCTURES = new Event('SET_STRUCTURES');
export const UPDATE_SELECTED_STRUCTURE_ID = new Event(
  'SET_SELECTED_STRUCTURE_ID'
);
export const UPDATE_EXPERIMENTS = new Event('SET_EXPERIMENTS');
export const UPDATE_SELECTED_EXPERIMENT_ID = new Event(
  'SET_SELECTED_EXPERIMENT_ID'
);
export const UPDATE_MONITORINGS = new Event('SET_MONITORINGS');
export const UPDATE_SELECTED_MONITORING_ID = new Event(
  'SET_SELECTED_MONITORING_ID'
);
