export const UPDATE_STATE = new Event('UPDATE_STATE');
export const UPDATE_STRUCTURES = new Event('UPDATE_STRUCTURES');
export const UPDATE_SELECTED_STRUCTURE_ID = new Event(
  'UPDATE_SELECTED_STRUCTURE_ID'
);
export const UPDATE_EXPERIMENTS = new Event('UPDATE_EXPERIMENTS');
export const UPDATE_SELECTED_EXPERIMENT_ID = new Event(
  'UPDATE_SELECTED_EXPERIMENT_ID'
);
export const UPDATE_MONITORS = new Event('UPDATE_MONITORS');
export const UPDATE_SELECTED_MONITOR_ID = new Event(
  'UPDATE_SELECTED_MONITOR_ID'
);
